lr: 0.001
seed: 2
if_cuda: True
gamma: 0.5
log_dir: 'logs'
train_batch: 8
val_batch: 8
test_batch: 4
num_workers: 8
model_name: 'encoder-decoder-64'
data_filepath: '/data/physics_prediction_v2/data'
dataset: 'reaction_diffusion'
num_frames: 100
lr_schedule: [20, 50, 100, 300, 600]
lda: 10.0
beta: 1.0
num_gpus: 1
epochs: 1000