lr: 0.0002
seed: 1
if_cuda: True
gamma: 0.5
log_dir: 'logs'
train_batch: 8
val_batch: 8
test_batch: 8
num_workers: 8
model_name: 'encoder-decoder-64'
data_filepath: '/data/physics_prediction_v2/data'
dataset: 'single_pendulum'
num_frames: 60
lr_schedule: [20, 50, 100, 300, 600]
lda1: 0.1
lda2: 1.0
lda3: 0.0
beta: 1.0
num_gpus: 1
epochs: 500